name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # runs at 20:05 Vilnius time
    - cron: "5 17 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
