name: Update Readme.md

on:
  workflow_dispatch:
  schedule:
    - cron: '30 * * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: 'chore: update waka-readme graph with new metrics'
          COMMITTER_NAME: gh-actions-bot
          SHOW_TOTAL: true
      - uses: vnphanquang/monkeytype-readme@main
        with:
          monkeytype_api_key: ${{ secrets.MONKEYTYPE_API_KEY }}
          mode: 'time'
          mode2: '60'
          style: 'flat'
          logoVariant: 'two'
          label: ''
