name: Update Readme.md

on:
  workflow_dispatch:
  schedule:
    - cron: '20 */4 * * *'

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          COMMIT_MESSAGE: 'chore: update waka-readme graph with new metrics'
          COMMITTER_NAME: gh-actions-bot
          SHOW_TOTAL: true
